### PR TITLE
md doc

### PR DESCRIPTION
**Pull request by gotocoffee1**
Hey I added some features to libedssharp that could be useful for others:

- added documentation generation to markdown makes it possible to compile the docs to any format (e.g. pdf) via [pandoc](https://pandoc.org/)
- fixed saving of low and high values
- it is now possible to add descriptions to subobjects since the CiA documents have subobject descriptions and xdd also supports them I thought it would be useful
- changed from #pragma once to ifdef for older compilers

### CODE REVIEW

**Comment by robincornelius** [comment]
Thanks for this, i've been meaning to get some work done on this project and push an update. But so far not finding any time. But i will integrate this its a great idea

**Comment by martinwag** [comment]
I've tried this, I think it's a great idea too.

I've found one little problem. When using visible string variables without default value, one can use "\0\0\0\0" as default value to generate a string variable in the requested length. This is output to markdown as " | Default Value | \0\0\0\0 | ", which gives an error in pandoc compile.

**Comment by martinwag** [comment]
This also breaks eds export for me. I don't think this is because of markdown export, but one of the other two changes.

**Comment by robincornelius** [comment]
Just needed a null/empty string check on the high/low limit variables

**Pull request merged**
