### PR TITLE
some small changes and bugfixes

### PR DESCRIPTION
**Pull request by s-fuchs**
I'm not sure about 7c6f3b3 because i'm not that familiar with C#.

### CODE REVIEW

**Comment by robincornelius** [comment]
7c6f3b3 is valid, in that case f is always valid (its compile time static) but the actual value field of f could be null as that is the specific implementation of f.  So a null check against f.value is ok. really we should not be getting nulls propagating this far down the exporter but its really good to guard against these things anyway and at some point i'll look at a higher level to see if things should be defaulted to something not null

I'm checking 5eb4c35, i thought I was correct before but may be the same regression that effected record objects also effected arrays

**Comment by s-fuchs** [comment]
With 5eb4c35 the values of maxSubIndex in my CO_OD.c made with libedsharp are the same as created with the old canopennode editor :+1: 

Take 0x1018 (Identity): It has 5 sub-objects, so maxSubIndex  should be 4 

Quote CO_SDO.h:
>     /** Number of (sub-objects - 1). If Object Type is variable, then
    maxSubIndex is 0, otherwise maxSubIndex is equal or greater than 1. */
    uint8_t             maxSubIndex;

**Comment by s-fuchs** [comment]
If you incorporate 3a3d6c5, you must also include b61dbdf or something like...
I was not aware how the data inside the table is used :-/

**Comment by robincornelius** [comment]
Ok not a problem. I'll take a look at how i'm handling the data in the PDO table. I expect something cleaner can be done. But for the moment i'll pull in your patch and fix.

5eb4c35  understand what i was thinking now. There is an oddity in canopennode that still has the size of array within the array define AND in the object dictionary.  so looking at 0x1018 it is defined as {0x4L, 0x0000L, 0x0000L, 0x0000L, 0x0000L} so it has 5 entries but entry 0 is a dummy one and not used.

I'm working through a different issue at the moment as i'm having an issue reading back some OD entries over the Can bus not sure if its related or not but will pull once i've found the other problem

**Comment by robincornelius** [comment]
Found the issue :-/ There is an incomplete section, i've opened #15 as currently the structure for the record objects are not generating. Its a stub in the exporter.

**Pull request merged**
